create database db;
use db;

create table DEPARTMENT
(
	DEPID INT PRIMARY KEY,
	NAME VARCHAR(50)
);

CREATE  TABLE EMPLOYEES
(
	EMPID INT PRIMARY KEY,
	DEPID INT FOREIGN KEY REFERENCES DEPARTMENT (DEPID),
	NAME  VARCHAR(50),
	DOB   DATETIME
);

CREATE TABLE SALARIES
(
	SALID		INT PRIMARY KEY,
	PERSONID	INT FOREIGN KEY REFERENCES EMPLOYEES (EMPID),
	GROSSS		MONEY,
	SALDATE		DATETIME
);